### ISSUE TITLE
Consistent language for WebAssembly support

### ISSUE THREAD

**Issue by danielledeleo** [nginx/unit-docs#141]
Throughout the docs site and several other places we lack precise definitions for what kind of WebAssembly support Unit offers. There is also extra confusion because our two incompatible Wasm implementations are documented side-by-side. Any old references to `unit-wasm` should be clearly marked as deprecated or removed entirely.

## What do we support anyway?

In order of specificity:
- WebAssembly
- [WASI 0.2](https://github.com/WebAssembly/WASI/blob/f45e72e5294e990c23d548eea32fd35c80525fd6/preview2/README.md?plain=1#L10) (previously known as preview 2)
- [wasi-http/proxy:0.2.0](https://github.com/WebAssembly/wasi-http/blob/a81c61fc584278f801393b22289840a439e51f50/wit/proxy.wit#L26-L38)

## Tasks
- [ ] Define _exact_ terminology to use when describing Unit's WebAssembly support and stick to it
- [ ] Update all references across all Unit repositories (not an exhaustive list)
  - [ ] [nginx/unit-docs](https://github.com/nginx/unit-docs/)
  - [ ] [nginx/unit](https://github.com/nginx/unit/) (README, manpages, --help, CLI, ...)
  - [ ] internal docs (Confluence)

**Comment by avahahn** [comment]
https://github.com/nginx/unit-wasm/pull/28
